#!/bin/sh

# ~script by thatcher
# move the uploads dir to a safe; persistent place under data and symlink it to the place
# where wordpress expects it.
# Changes to the site should be done on the local version and then pushed.

echo "setting up perisstent static dir"
if [ -d ~/data/uploads ]
then
      rm -rf ~/current/wp-content/uploads
else
      mkdir -p ~/data
      mv ~/current/wp-content/uploads ~/data/uploads
fi

ln -s ~/data/uploads ~/current/wp-content/uploads

rm ~/current/wp-salt.php
ln -s ~/data/wp-salt.php ~/current/wp-salt.php

# setup the databases
php ~/code/setupdb.php
